name: flutter_echarts
description: A data visualization charts library, based on Apache ECharts, able to build advanced charts like WebGL 3D, GIS map, etc.
version: 2.4.0
homepage: https://github.com/entronad/flutter_echarts

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.0
  webview_flutter_android: ^3.7.0
  webview_flutter_wkwebview: ^3.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
